name: Update Flipper Application Catalog

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'application.fam'

jobs:
  update-catalog:
    runs-on: ubuntu-latest

    steps:
      - uses: zacharyweiss/flipper-app-catalog-action@v1.0
        id: update_manifest
        with:
          CATALOG_UPDATE_TOKEN: ${{ secrets.CATALOG_UPDATE_TOKEN }}
    
      # TODO: Auto-PR?
