name: Build

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  firmware_version: '0.78.1'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Flipper Zero Firmware
        uses: actions/checkout@v3
        with:
          repository: 'flipperdevices/flipperzero-firmware'
          ref: ${{ env.firmware_version }}
          submodules: true
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'applications_user/FlipBIP'
      - name: Build
        run: ./fbt COMPACT=1 DEBUG=0 faps