name: FlipperZero

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      uses: oleksiikutuzov/flipperzero-ufbt-action@v1
      with:
        channel: release
