name: Build dev

on:
  push:
    branches:
      - main

jobs:
  build_rc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: oleksiikutuzov/flipperzero-ufbt-action@main
        with:
          channel: dev